name: Deploy Portal de Eventos PGSS

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for development
      if: github.ref == 'refs/heads/development'
      run: npm run build:dev
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL_DEV }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY_DEV }}
        VITE_STORAGE_BUCKET_NAME: ${{ secrets.VITE_STORAGE_BUCKET_NAME_DEV }}
        VITE_APP_URL: ${{ secrets.VITE_APP_URL_DEV }}
        VITE_APP_ENV: development
        VITE_IS_PRODUCTION: false
        
    - name: Build for production
      if: github.ref == 'refs/heads/main'
      run: npm run build:prod
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL_PROD }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY_PROD }}
        VITE_STORAGE_BUCKET_NAME: ${{ secrets.VITE_STORAGE_BUCKET_NAME_PROD }}
        VITE_APP_URL: ${{ secrets.VITE_APP_URL_PROD }}
        VITE_APP_ENV: production
        VITE_IS_PRODUCTION: true
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        
    - name: Deploy to development
      if: github.ref == 'refs/heads/development'
      run: |
        echo "Deploying to development environment..."
        # Aqui você adicionaria os comandos para deploy no ambiente de desenvolvimento
        
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production environment..."
        # Aqui você adicionaria os comandos para deploy no ambiente de produção 